# Model configuration
model:
  num_classes: 1000
  patch_size: [16, 16]   # tuple input
  hidden_size: 768
  classifier: "token"
  representation_size: null
  deterministic: false
  head_bias_init: 0.0
  head_kernel_zero_init: true
  encoder:
    num_layers: 12
    num_heads: 12
    mlp_dim: 3072
    attention_dropout: 0.0
    dropout: 0.1
    moe:
      layers: [2, 4, 6, 8]  
      num_experts: 16
      group_size: 1
      router:
        num_selected_experts: 2
        noise_std: 0.125

# Training configuration
training:
  num_epochs: 100
  batch_size: 64
  learning_rate: 0.01
  weight_decay: 0.0001
  patience: 5
  checkpoint_path: "vmoe_best.pth"

# Dataset configuration
dataset:
  imagenet_path: "/path/to/imagenet"
  num_workers: 4
  image_size: 32

